import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import compiledPlugin from "@compiled/babel-plugin";
import stripRuntime from "@compiled/babel-plugin-strip-runtime";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: [
          "@atlaskit/tokens/babel-plugin",
          [
            compiledPlugin,
            {
              transformerBabelPlugins: ["@atlaskit/tokens/babel-plugin"],
              importSources: ["@compiled/react", "@atlaskit/css"],
            },
          ],
          stripRuntime,
        ],
      },
    }),
    // ── PWA: offline-first mandate from HCI research ──────────────────────
    // Service Worker is generated by Workbox via vite-plugin-pwa.
    // Strategy: NetworkFirst for API calls (fresh data when online),
    //           CacheFirst for app shell (instant cold-start when offline).
    VitePWA({
      registerType: "autoUpdate",
      workbox: {
        // Cache the app shell (HTML + JS bundles) so the portal launches
        // instantly even with zero connectivity.
        globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
        runtimeCaching: [
          {
            // API calls: try network first, fall back to cache.
            urlPattern: /\/api\/.*/i,
            handler: "NetworkFirst",
            options: {
              cacheName: "usrp-api-cache",
              expiration: { maxEntries: 200, maxAgeSeconds: 86_400 },
              networkTimeoutSeconds: 10,
            },
          },
          {
            // Audio guidance files for AudioTooltip — cache aggressively.
            urlPattern: /\/audio\/.*/i,
            handler: "CacheFirst",
            options: {
              cacheName: "usrp-audio-cache",
              expiration: { maxEntries: 50, maxAgeSeconds: 2_592_000 },
            },
          },
        ],
      },
      manifest: {
        name: "USRP Applicant Portal",
        short_name: "USRP",
        description: "Rwanda unified security recruitment — applicant portal",
        theme_color: "#0052CC",
        background_color: "#FFFFFF",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
          {
            src: "/icons/icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any maskable",
          },
        ],
      },
    }),
  ],
  build: {
    target: "es2022",
    sourcemap: true,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("@atlaskit")) return "atlaskit";
          if (id.includes("@tanstack")) return "tanstack";
          if (id.includes("workbox")) return "workbox";
        },
      },
    },
  },
  server: {
    port: 3000,
    strictPort: true,
    proxy: {
      "/api": {
        target: process.env["VITE_BFF_URL"] ?? "http://localhost:4020",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ""),
      },
    },
  },
});
