// contract-drift selftest: assertions must match the checker’s actual diagnostics.
import { extractAll, extractService } from './extract.ts';
import { gateA, gateB, gateC, type Manifest, type RouteFactLike } from './drift.ts';
const FIXTURE_SERVICES = new URL('../fixtures/backend/services', import.meta.url).pathname;
let passed = 0; const failures: string[] = [];
function assert(condition: boolean, what: string): void { if (condition) passed += 1; else failures.push(what); }
function assertEqual(actual: unknown, expected: unknown, what: string): void { assert(JSON.stringify(actual) === JSON.stringify(expected), `${what}\n      expected ${JSON.stringify(expected)}\n      actual   ${JSON.stringify(actual)}`); }
const alpha = extractService(FIXTURE_SERVICES, 'alpha-service');
assertEqual(alpha.problems, [], 'alpha: extractor reports no problems');
assertEqual([...alpha.pathConstants.entries()].sort(), [['ALPHA_DUAL_PATH','/v1/alpha/dual'],['ALPHA_OFFICER_PATH','/v1/alpha/officer'],['ALPHA_PUBLIC_PATH','/v1/alpha/public']], 'alpha: path constants');
const alphaByPath = new Map(alpha.routes.map((r) => [r.path, r]));
assertEqual(alphaByPath.get('/v1/alpha/officer')?.auth, ['officer'], 'alpha: single-kind');
assertEqual(alphaByPath.get('/v1/alpha/dual')?.auth, ['system','officer'], 'alpha: array-kind');
assertEqual(alphaByPath.get('/v1/alpha/public')?.auth, ['none'], 'alpha: public');
assert(alpha.readinessCallback, 'alpha: readiness'); assert(alpha.mountedFactories.includes('alphaRoutes'), 'alpha: mounted factory');
const beta = extractService(FIXTURE_SERVICES, 'beta-service'); assertEqual(beta.problems, [], 'beta: extractor');
const betaByKey = new Map(beta.routes.map((r) => [`${r.method} ${String(r.path)}`, r]));
assertEqual(betaByKey.get('GET /v1/beta/me')?.auth, ['applicant-session'], 'beta: applicant session');
assert(betaByKey.has('POST /v1/beta/thing') && betaByKey.has('GET /v1/beta/thing'), 'beta: two methods'); assert(betaByKey.has('GET /v1/beta/inline-key'), 'beta: inline route');
const gamma = extractService(FIXTURE_SERVICES, 'gamma-service'); assert(!gamma.readinessCallback, 'gamma: no readiness'); assert(!gamma.routes.some((r) => r.method === 'DELETE'), 'gamma: commented route');
const extracted = extractAll(FIXTURE_SERVICES); const c = gateC(extracted); const orphan = c.findings.filter((f) => f.message.includes('GAMMA_ORPHAN_PATH'));
assert(orphan.length === 1, `gate C: orphan caught exactly once (got ${orphan.length})`); assert(orphan[0]?.message.includes('not present in main.ts routes[]') === true, 'gate C: message names the actual failure'); assert(!c.findings.some((f) => f.message.includes('GAMMA_MOUNTED_PATH')), 'gate C: mounted route not reported');
const cleanManifest: Manifest = { backendSha: 'fixture', services: {'alpha-service': {controllerDir:'services/alpha-service/src/adapters/http', readinessCallback:true, routes:[{method:'POST',path:'/v1/alpha/officer',auth:['officer'],constant:'ALPHA_OFFICER_PATH',controller:'one.controller.ts',mounted:true},{method:'POST',path:'/v1/alpha/dual',auth:['system','officer'],constant:'ALPHA_DUAL_PATH',controller:'one.controller.ts',mounted:true},{method:'POST',path:'/v1/alpha/public',auth:['none'],constant:'ALPHA_PUBLIC_PATH',controller:'one.controller.ts',mounted:true}]}}};
const clean = gateB(cleanManifest, extracted); assertEqual(clean.findings, [], 'gate B clean'); assert(clean.assertions > 0, 'gate B assertions'); const clone = (): Manifest => JSON.parse(JSON.stringify(cleanManifest)) as Manifest;
const missing = clone(); (missing.services['alpha-service']!.routes as unknown[]).push({method:'DELETE',path:'/v1/alpha/gone',auth:['officer'],constant:null,controller:'one.controller.ts',mounted:true}); assert(gateB(missing, extracted).findings.some((f)=>f.message.includes('no route registration')), 'gate B missing');
const authDrift = clone(); (authDrift.services['alpha-service']!.routes[0] as {readonly auth: readonly string[]}).auth=['system']; assert(gateB(authDrift, extracted).findings.some((f)=>f.message.includes('auth kind drifted')), 'gate B auth');
const constDrift = clone(); (constDrift.services['alpha-service']!.routes[0] as {constant:string}).constant='ALPHA_RENAMED_PATH'; assert(gateB(constDrift, extracted).findings.some((f)=>f.message.includes('no longer exports')), 'gate B constant');
const readinessDrift = clone(); (readinessDrift.services['alpha-service'] as {readinessCallback:boolean}).readinessCallback=false; assert(gateB(readinessDrift, extracted).findings.some((f)=>f.message.includes('readiness callback')), 'gate B readiness');
const extraBackendRoute = clone(); (extraBackendRoute.services['alpha-service']!.routes as unknown[]).splice(2,1); assert(gateB(extraBackendRoute, extracted).findings.some((f)=>f.message.includes('NEW BACKEND ROUTE')), 'gate B extra');
const table: RouteFactLike[] = [{service:'alpha-service',operationId:'alphaOfficer',method:'POST',path:'/v1/alpha/officer',auth:['officer'],reach:'browser'},{service:'alpha-service',operationId:'alphaDual',method:'POST',path:'/v1/alpha/dual',auth:['system','officer'],reach:'service-internal'},{service:'alpha-service',operationId:'alphaPublic',method:'POST',path:'/v1/alpha/public',auth:['none'],reach:'browser'},{service:'alpha-service',operationId:'alphaHealth',method:'GET',path:'/health',auth:['none'],reach:'service-internal'},{service:'alpha-service',operationId:'alphaReady',method:'GET',path:'/ready',auth:['none'],reach:'service-internal'}];
assertEqual(gateA(table, cleanManifest).findings, [], 'gate A clean'); assert(gateA(table.filter((r)=>r.operationId!=='alphaDual'),cleanManifest).findings.some((f)=>f.message.includes('MISSING ROUTE')), 'gate A missing'); assert(gateA([...table,{service:'alpha-service',operationId:'invented',method:'POST',path:'/v1/alpha/invented',auth:['officer'],reach:'browser'}],cleanManifest).findings.some((f)=>f.message.includes('EXTRA ROUTE')), 'gate A extra'); assert(gateA(table.map((r)=>r.operationId==='alphaOfficer'?{...r,auth:['system']}:r),cleanManifest).findings.some((f)=>f.message.includes('CHANGED AUTH KIND')), 'gate A auth'); assert(gateA(table.map((r)=>r.operationId==='alphaDual'?{...r,reach:'browser'}:r),cleanManifest).findings.some((f)=>f.message.includes('REACH MISMATCH')), 'gate A reach'); assert(gateA(table.map((r)=>r.operationId==='alphaOfficer'?{...r,method:'PUT'}:r),cleanManifest).findings.some((f)=>f.message.includes('MISSING ROUTE')), 'gate A method'); assert(gateA(table.filter((r)=>r.path!=='/ready'),cleanManifest).findings.some((f)=>f.message.includes('/ready')), 'gate A ready');
if (failures.length > 0) { console.error(`contract-drift selftest FAILED — ${failures.length} of ${passed + failures.length}`); for (const failure of failures) console.error(`  ✗ ${failure}`); process.exit(1); } console.log(`contract-drift selftest OK — ${passed} assertions`);
